apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    app.kubernetese.io/name: mysql
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  